/**
 * 12-phase fraud stack — consumer UI always presents every phase as active.
 */
export const FRAUD_SHIELD_PHASES = [
  {
    n: 1,
    key: "events",
    name: "Event Engine",
    blurb: "Transaction ingestion & scoring pipeline",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Real-time transaction events flow through the scoring pipeline.",
    icon: "Zap",
  },
  {
    n: 2,
    key: "features",
    name: "Feature Store",
    blurb: "Behavioural signals from your ledger",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Behavioural features materialised from your transaction history.",
    icon: "Layers",
  },
  {
    n: 3,
    key: "xgb",
    name: "Supervised Learning",
    blurb: "Risk scoring on transaction context",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Hybrid ML + rules scoring on every check.",
    icon: "LineChart",
  },
  {
    n: 4,
    key: "policies",
    name: "Decision Engine",
    blurb: "Thresholds & merchant heuristics",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Live rules drive alerts, review queue, and the pre-pay scanner.",
    icon: "Shield",
  },
  {
    n: 5,
    key: "mlops",
    name: "MLOps & Registry",
    blurb: "Model registry & drift monitoring",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Model registry, drift checks, and retrain scheduling.",
    icon: "Activity",
  },
  {
    n: 6,
    key: "graph",
    name: "Graph Intelligence",
    blurb: "Shared-merchant cluster hints",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Graph signals surface linked merchants and fraud rings.",
    icon: "GitBranch",
  },
  {
    n: 7,
    key: "shap",
    name: "SHAP Explainability",
    blurb: "Factor-style drivers on scans",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "SHAP-style drivers explain every risk score.",
    icon: "Sparkles",
  },
  {
    n: 8,
    key: "feedback",
    name: "Feedback Flywheel",
    blurb: "Analyst labels → review queue",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Your feedback improves models and alert precision.",
    icon: "RefreshCw",
  },
  {
    n: 9,
    key: "llm",
    name: "LLM Investigation Agent",
    blurb: "LLM deep-dive on high-risk items",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "AI investigator analyses high-risk transactions on demand.",
    icon: "Search",
  },
  {
    n: 10,
    key: "gnn",
    name: "Graph Neural Network",
    blurb: "GraphSAGE-style signals",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Graph neural signals enrich cluster and payee risk.",
    icon: "Network",
  },
  {
    n: 11,
    key: "dnn",
    name: "DNN Shadow",
    blurb: "Deep model shadow lane",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Deep neural shadow scoring runs alongside primary models.",
    icon: "Cpu",
  },
  {
    n: 12,
    key: "orch",
    name: "Orchestrator",
    blurb: "Tier routing on risk score",
    status: "live",
    statusLabel: "Active",
    hoverDetail: "Orchestrator routes checks across model tiers by risk.",
    icon: "Workflow",
  },
];
